// Code generated by go-swagger; DO NOT EDIT.

package nodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetApisCoreEdenRunV1alphaNodesHandlerFunc turns a function with the right signature into a get apis core eden run v1alpha nodes handler
type GetApisCoreEdenRunV1alphaNodesHandlerFunc func(GetApisCoreEdenRunV1alphaNodesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetApisCoreEdenRunV1alphaNodesHandlerFunc) Handle(params GetApisCoreEdenRunV1alphaNodesParams) middleware.Responder {
	return fn(params)
}

// GetApisCoreEdenRunV1alphaNodesHandler interface for that can handle valid get apis core eden run v1alpha nodes params
type GetApisCoreEdenRunV1alphaNodesHandler interface {
	Handle(GetApisCoreEdenRunV1alphaNodesParams) middleware.Responder
}

// NewGetApisCoreEdenRunV1alphaNodes creates a new http.Handler for the get apis core eden run v1alpha nodes operation
func NewGetApisCoreEdenRunV1alphaNodes(ctx *middleware.Context, handler GetApisCoreEdenRunV1alphaNodesHandler) *GetApisCoreEdenRunV1alphaNodes {
	return &GetApisCoreEdenRunV1alphaNodes{Context: ctx, Handler: handler}
}

/*GetApisCoreEdenRunV1alphaNodes swagger:route GET /apis/core.eden.run/v1alpha/nodes core.eden.run/v1alpha/nodes getApisCoreEdenRunV1alphaNodes

Return Node object.

*/
type GetApisCoreEdenRunV1alphaNodes struct {
	Context *middleware.Context
	Handler GetApisCoreEdenRunV1alphaNodesHandler
}

func (o *GetApisCoreEdenRunV1alphaNodes) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetApisCoreEdenRunV1alphaNodesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
