// Code generated by go-swagger; DO NOT EDIT.

package nodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*PatchApisCoreEdenRunV1alphaNodesDefault Default error sample response

swagger:response patchApisCoreEdenRunV1alphaNodesDefault
*/
type PatchApisCoreEdenRunV1alphaNodesDefault struct {
	_statusCode int
}

// NewPatchApisCoreEdenRunV1alphaNodesDefault creates PatchApisCoreEdenRunV1alphaNodesDefault with default headers values
func NewPatchApisCoreEdenRunV1alphaNodesDefault(code int) *PatchApisCoreEdenRunV1alphaNodesDefault {
	if code <= 0 {
		code = 500
	}

	return &PatchApisCoreEdenRunV1alphaNodesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the patch apis core eden run v1alpha nodes default response
func (o *PatchApisCoreEdenRunV1alphaNodesDefault) WithStatusCode(code int) *PatchApisCoreEdenRunV1alphaNodesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the patch apis core eden run v1alpha nodes default response
func (o *PatchApisCoreEdenRunV1alphaNodesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *PatchApisCoreEdenRunV1alphaNodesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
