// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/galexrt/edenconfmgmt/pkg/apis/nodes/v1alpha/api.proto

package v1alpha

import (
	fmt "fmt"
	v1alpha "github.com/galexrt/edenconfmgmt/pkg/apis/core/v1alpha"
	v1alpha1 "github.com/galexrt/edenconfmgmt/pkg/apis/events/v1alpha"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Node struct {
	// Metadata for Node object.
	Metadata *v1alpha.ObjectMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Spec for Node.
	Spec                 *NodeSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_72e58667dd6394e3, []int{0}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetMetadata() *v1alpha.ObjectMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Node) GetSpec() *NodeSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

type NodeSpec struct {
	// FQDN of Node.
	Fqdn string `protobuf:"bytes,3,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	// IP addresses of Node.
	Addresses            []string `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeSpec) Reset()         { *m = NodeSpec{} }
func (m *NodeSpec) String() string { return proto.CompactTextString(m) }
func (*NodeSpec) ProtoMessage()    {}
func (*NodeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_72e58667dd6394e3, []int{1}
}

func (m *NodeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeSpec.Unmarshal(m, b)
}
func (m *NodeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeSpec.Marshal(b, m, deterministic)
}
func (m *NodeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeSpec.Merge(m, src)
}
func (m *NodeSpec) XXX_Size() int {
	return xxx_messageInfo_NodeSpec.Size(m)
}
func (m *NodeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_NodeSpec proto.InternalMessageInfo

func (m *NodeSpec) GetFqdn() string {
	if m != nil {
		return m.Fqdn
	}
	return ""
}

func (m *NodeSpec) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type AddNodeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNodeResponse) Reset()         { *m = AddNodeResponse{} }
func (m *AddNodeResponse) String() string { return proto.CompactTextString(m) }
func (*AddNodeResponse) ProtoMessage()    {}
func (*AddNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_72e58667dd6394e3, []int{2}
}

func (m *AddNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNodeResponse.Unmarshal(m, b)
}
func (m *AddNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNodeResponse.Marshal(b, m, deterministic)
}
func (m *AddNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNodeResponse.Merge(m, src)
}
func (m *AddNodeResponse) XXX_Size() int {
	return xxx_messageInfo_AddNodeResponse.Size(m)
}
func (m *AddNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddNodeResponse proto.InternalMessageInfo

type UpdateNodeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNodeResponse) Reset()         { *m = UpdateNodeResponse{} }
func (m *UpdateNodeResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateNodeResponse) ProtoMessage()    {}
func (*UpdateNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_72e58667dd6394e3, []int{3}
}

func (m *UpdateNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNodeResponse.Unmarshal(m, b)
}
func (m *UpdateNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNodeResponse.Marshal(b, m, deterministic)
}
func (m *UpdateNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNodeResponse.Merge(m, src)
}
func (m *UpdateNodeResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateNodeResponse.Size(m)
}
func (m *UpdateNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNodeResponse proto.InternalMessageInfo

type DeleteNodeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteNodeResponse) Reset()         { *m = DeleteNodeResponse{} }
func (m *DeleteNodeResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteNodeResponse) ProtoMessage()    {}
func (*DeleteNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_72e58667dd6394e3, []int{4}
}

func (m *DeleteNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNodeResponse.Unmarshal(m, b)
}
func (m *DeleteNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNodeResponse.Marshal(b, m, deterministic)
}
func (m *DeleteNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNodeResponse.Merge(m, src)
}
func (m *DeleteNodeResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteNodeResponse.Size(m)
}
func (m *DeleteNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNodeResponse proto.InternalMessageInfo

type NodeWatchResponse struct {
	// Event info for watch response.
	Event *v1alpha1.Event `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// Node for watch response.
	Node                 *Node    `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeWatchResponse) Reset()         { *m = NodeWatchResponse{} }
func (m *NodeWatchResponse) String() string { return proto.CompactTextString(m) }
func (*NodeWatchResponse) ProtoMessage()    {}
func (*NodeWatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_72e58667dd6394e3, []int{5}
}

func (m *NodeWatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeWatchResponse.Unmarshal(m, b)
}
func (m *NodeWatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeWatchResponse.Marshal(b, m, deterministic)
}
func (m *NodeWatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeWatchResponse.Merge(m, src)
}
func (m *NodeWatchResponse) XXX_Size() int {
	return xxx_messageInfo_NodeWatchResponse.Size(m)
}
func (m *NodeWatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeWatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeWatchResponse proto.InternalMessageInfo

func (m *NodeWatchResponse) GetEvent() *v1alpha1.Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *NodeWatchResponse) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func init() {
	proto.RegisterType((*Node)(nil), "nodes.v1alpha.Node")
	proto.RegisterType((*NodeSpec)(nil), "nodes.v1alpha.NodeSpec")
	proto.RegisterType((*AddNodeResponse)(nil), "nodes.v1alpha.AddNodeResponse")
	proto.RegisterType((*UpdateNodeResponse)(nil), "nodes.v1alpha.UpdateNodeResponse")
	proto.RegisterType((*DeleteNodeResponse)(nil), "nodes.v1alpha.DeleteNodeResponse")
	proto.RegisterType((*NodeWatchResponse)(nil), "nodes.v1alpha.NodeWatchResponse")
}

func init() {
	proto.RegisterFile("github.com/galexrt/edenconfmgmt/pkg/apis/nodes/v1alpha/api.proto", fileDescriptor_72e58667dd6394e3)
}

var fileDescriptor_72e58667dd6394e3 = []byte{
	// 473 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x18, 0xec, 0x12, 0x43, 0x9a, 0x0f, 0x10, 0xea, 0x02, 0x22, 0xb2, 0x8a, 0x15, 0x72, 0x21, 0x52,
	0x85, 0x0d, 0xad, 0x84, 0x38, 0x20, 0xa0, 0x28, 0xc0, 0x09, 0x90, 0x5c, 0x7e, 0x24, 0x6e, 0x9b,
	0xdd, 0x2f, 0x8e, 0x21, 0xf6, 0x6e, 0xbd, 0x9b, 0x88, 0x23, 0x8f, 0xc0, 0x0b, 0xf0, 0x3e, 0x3d,
	0x72, 0xe4, 0x48, 0xc3, 0x8b, 0xa0, 0xdd, 0x38, 0x0d, 0x75, 0x1c, 0x29, 0xe2, 0xb6, 0xdf, 0xec,
	0xec, 0x7c, 0x99, 0x19, 0xc5, 0xf0, 0x2c, 0x49, 0xcd, 0x68, 0x32, 0x08, 0xb9, 0xcc, 0xa2, 0x84,
	0x8d, 0xf1, 0x6b, 0x61, 0x22, 0x14, 0x98, 0x73, 0x99, 0x0f, 0xb3, 0x24, 0x33, 0x91, 0xfa, 0x92,
	0x44, 0x4c, 0xa5, 0x3a, 0xca, 0xa5, 0x40, 0x1d, 0x4d, 0x1f, 0xb0, 0xb1, 0x1a, 0x31, 0x0b, 0x85,
	0xaa, 0x90, 0x46, 0xd2, 0xab, 0xee, 0x22, 0x2c, 0x2f, 0xfc, 0x7b, 0xff, 0x0a, 0xca, 0x44, 0x46,
	0x8e, 0x35, 0x98, 0x0c, 0xdd, 0xe4, 0x06, 0x77, 0x9a, 0xbf, 0xf6, 0x9f, 0x6e, 0xbc, 0x9f, 0xcb,
	0x02, 0x57, 0xd7, 0xfb, 0x87, 0x1b, 0x0b, 0xe0, 0x14, 0x73, 0x53, 0xe3, 0xa0, 0x9b, 0x81, 0xf7,
	0x46, 0x0a, 0xa4, 0x8f, 0x60, 0x3b, 0x43, 0xc3, 0x04, 0x33, 0xac, 0x4d, 0x3a, 0xa4, 0x77, 0x79,
	0x7f, 0x37, 0xb4, 0x5b, 0x17, 0xde, 0xc2, 0xb7, 0x83, 0xcf, 0xc8, 0xcd, 0xeb, 0x92, 0x13, 0x9f,
	0xb1, 0xe9, 0x1e, 0x78, 0x5a, 0x21, 0x6f, 0x5f, 0x70, 0xaf, 0x6e, 0x85, 0xe7, 0x22, 0x09, 0xad,
	0xf8, 0x91, 0x42, 0x1e, 0x3b, 0x52, 0xf7, 0x31, 0x6c, 0x2f, 0x10, 0x4a, 0xc1, 0x1b, 0x1e, 0x8b,
	0xbc, 0xdd, 0xe8, 0x90, 0x5e, 0x2b, 0x76, 0x67, 0xba, 0x0b, 0x2d, 0x26, 0x44, 0x81, 0x5a, 0xa3,
	0x6e, 0x7b, 0x9d, 0x46, 0xaf, 0x15, 0x2f, 0x81, 0xee, 0x0e, 0x5c, 0x3b, 0x14, 0xc2, 0x0a, 0xc4,
	0xa8, 0x95, 0xcc, 0x35, 0x76, 0x6f, 0x00, 0x7d, 0xaf, 0x04, 0x33, 0x58, 0x45, 0xfb, 0x38, 0xc6,
	0x0a, 0x9a, 0xc2, 0x8e, 0x9d, 0x3f, 0x32, 0xc3, 0x47, 0x0b, 0x90, 0xee, 0xc1, 0x45, 0x17, 0x4e,
	0xe9, 0xfa, 0x66, 0x38, 0x8f, 0xea, 0xcc, 0xc0, 0x0b, 0x3b, 0xc6, 0x73, 0x0e, 0xbd, 0x0b, 0x9e,
	0xb5, 0x57, 0x7a, 0xbd, 0x5e, 0xe3, 0x35, 0x76, 0x84, 0xfd, 0x1f, 0x0d, 0xb8, 0x62, 0x47, 0x7d,
	0x84, 0xc5, 0x34, 0xe5, 0x48, 0x5f, 0x42, 0xf3, 0x03, 0x16, 0x3a, 0x95, 0x39, 0xad, 0x04, 0x5b,
	0xc2, 0x31, 0x1e, 0x4f, 0x50, 0x1b, 0xff, 0xf6, 0x9a, 0xdb, 0xf2, 0xe7, 0x1e, 0x40, 0xf3, 0x15,
	0x1a, 0x57, 0x59, 0xdd, 0x7a, 0xbf, 0x0e, 0xa4, 0x4f, 0xa0, 0x59, 0xe6, 0x56, 0xff, 0x28, 0xa8,
	0x80, 0x95, 0x90, 0x69, 0x1f, 0x60, 0x19, 0x72, 0xbd, 0xc4, 0x9d, 0x0a, 0xb8, 0x5a, 0x8a, 0x55,
	0x59, 0x96, 0xb2, 0x99, 0xca, 0x6a, 0x89, 0xb4, 0x0f, 0x2d, 0x57, 0xe0, 0x7a, 0x91, 0x4e, 0x0d,
	0x78, 0xae, 0xf3, 0xfb, 0xe4, 0xf9, 0xbb, 0x93, 0xd3, 0x80, 0xfc, 0x3a, 0x0d, 0xb6, 0xbe, 0xcd,
	0x02, 0x72, 0x32, 0x0b, 0xc8, 0xcf, 0x59, 0x40, 0x7e, 0xcf, 0x02, 0xf2, 0xfd, 0x4f, 0xb0, 0xf5,
	0xe9, 0xe1, 0xff, 0x7d, 0x18, 0x06, 0x97, 0xdc, 0x7f, 0xea, 0xe0, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xf7, 0xe1, 0xba, 0x6d, 0x59, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodesServiceClient is the client API for NodesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodesServiceClient interface {
	// Version returns the API version.
	Version(ctx context.Context, in *v1alpha.VersionRequest, opts ...grpc.CallOption) (*v1alpha.VersionResponse, error)
	// Get a Node.
	GetNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Node, error)
	// Add a Node.
	AddNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (*AddNodeResponse, error)
	// Update a Node.
	UpdateNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (*UpdateNodeResponse, error)
	// Delete a Node.
	DeleteNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (*DeleteNodeResponse, error)
	// Watch a Node.
	WatchNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (NodesService_WatchNodeClient, error)
}

type nodesServiceClient struct {
	cc *grpc.ClientConn
}

func NewNodesServiceClient(cc *grpc.ClientConn) NodesServiceClient {
	return &nodesServiceClient{cc}
}

func (c *nodesServiceClient) Version(ctx context.Context, in *v1alpha.VersionRequest, opts ...grpc.CallOption) (*v1alpha.VersionResponse, error) {
	out := new(v1alpha.VersionResponse)
	err := c.cc.Invoke(ctx, "/nodes.v1alpha.NodesService/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodesServiceClient) GetNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := c.cc.Invoke(ctx, "/nodes.v1alpha.NodesService/GetNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodesServiceClient) AddNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (*AddNodeResponse, error) {
	out := new(AddNodeResponse)
	err := c.cc.Invoke(ctx, "/nodes.v1alpha.NodesService/AddNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodesServiceClient) UpdateNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (*UpdateNodeResponse, error) {
	out := new(UpdateNodeResponse)
	err := c.cc.Invoke(ctx, "/nodes.v1alpha.NodesService/UpdateNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodesServiceClient) DeleteNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (*DeleteNodeResponse, error) {
	out := new(DeleteNodeResponse)
	err := c.cc.Invoke(ctx, "/nodes.v1alpha.NodesService/DeleteNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodesServiceClient) WatchNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (NodesService_WatchNodeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NodesService_serviceDesc.Streams[0], "/nodes.v1alpha.NodesService/WatchNode", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodesServiceWatchNodeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NodesService_WatchNodeClient interface {
	Recv() (*NodeWatchResponse, error)
	grpc.ClientStream
}

type nodesServiceWatchNodeClient struct {
	grpc.ClientStream
}

func (x *nodesServiceWatchNodeClient) Recv() (*NodeWatchResponse, error) {
	m := new(NodeWatchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NodesServiceServer is the server API for NodesService service.
type NodesServiceServer interface {
	// Version returns the API version.
	Version(context.Context, *v1alpha.VersionRequest) (*v1alpha.VersionResponse, error)
	// Get a Node.
	GetNode(context.Context, *Node) (*Node, error)
	// Add a Node.
	AddNode(context.Context, *Node) (*AddNodeResponse, error)
	// Update a Node.
	UpdateNode(context.Context, *Node) (*UpdateNodeResponse, error)
	// Delete a Node.
	DeleteNode(context.Context, *Node) (*DeleteNodeResponse, error)
	// Watch a Node.
	WatchNode(*Node, NodesService_WatchNodeServer) error
}

func RegisterNodesServiceServer(s *grpc.Server, srv NodesServiceServer) {
	s.RegisterService(&_NodesService_serviceDesc, srv)
}

func _NodesService_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1alpha.VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodesServiceServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodes.v1alpha.NodesService/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodesServiceServer).Version(ctx, req.(*v1alpha.VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodesService_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodesServiceServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodes.v1alpha.NodesService/GetNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodesServiceServer).GetNode(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodesService_AddNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodesServiceServer).AddNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodes.v1alpha.NodesService/AddNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodesServiceServer).AddNode(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodesService_UpdateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodesServiceServer).UpdateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodes.v1alpha.NodesService/UpdateNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodesServiceServer).UpdateNode(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodesService_DeleteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodesServiceServer).DeleteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodes.v1alpha.NodesService/DeleteNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodesServiceServer).DeleteNode(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodesService_WatchNode_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Node)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodesServiceServer).WatchNode(m, &nodesServiceWatchNodeServer{stream})
}

type NodesService_WatchNodeServer interface {
	Send(*NodeWatchResponse) error
	grpc.ServerStream
}

type nodesServiceWatchNodeServer struct {
	grpc.ServerStream
}

func (x *nodesServiceWatchNodeServer) Send(m *NodeWatchResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _NodesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nodes.v1alpha.NodesService",
	HandlerType: (*NodesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _NodesService_Version_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _NodesService_GetNode_Handler,
		},
		{
			MethodName: "AddNode",
			Handler:    _NodesService_AddNode_Handler,
		},
		{
			MethodName: "UpdateNode",
			Handler:    _NodesService_UpdateNode_Handler,
		},
		{
			MethodName: "DeleteNode",
			Handler:    _NodesService_DeleteNode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchNode",
			Handler:       _NodesService_WatchNode_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "github.com/galexrt/edenconfmgmt/pkg/apis/nodes/v1alpha/api.proto",
}
