graph LR
    Start-->User
    subgraph User
        User-->|uses|edenctl
    end
    subgraph Master
        User-->HTTPAPI
        HTTPAPI[HTTP API]-->Prometheus[Prometheus Metrics]
        edenctl-->GRPC[GRPC API]
        GRPC-->Interactive
        GRPC-->Serialization
        subgraph Objects
            Unmarshal-->|set defaults|Validation
            Validation-->StoreCacheAccess
        end
        subgraph DataStore + Cache
            StoreCacheAccess[Store + Cache Access]-->|Get, List, Update, Delete, Watch|dataStoreStoreInt[dataStore.Store Interface]
            dataStoreStoreInt-->|Get, Update, Delete, Watch|Cacher
            Cacher-.->|Implements|dataStoreStoreInt
            Cacher-->|Watches/Notifies|CacheInformer
            etcd-.->|Implements|dataStoreStoreInt
			Cacher-->|Store + Watch|etcd
            Cacher-->|Store|CacheAdapterMemory["Memory (go map[string]string)"]
        end
        subgraph Controller
            NodeStatus-->|Watch Nodes|dataStoreStoreInt
            VariablesUpdater-->|Reconciliation Loop|VariablesUpdater
            VariablesUpdater-->|Watch Variables, ClusterVariables + CVarsBindings|dataStoreStoreInt
            TaskBookController-->|Watch TaskBooks|dataStoreStoreInt
        end
        subgraph Scheduler
            Scheduler-->|Watch|dataStoreStoreInt
            subgraph Orchestration
                Serialization
                Interactive
            end
        end
        subgraph EventReactor
            EventReactor-->|Watch Events|dataStoreStoreInt
            EventReactor-->|Watch Triggers|dataStoreStoreInt
            EventReactor-->|Run Triggers|Trigger
            Trigger-->Scheduler
        end
    end
    subgraph Node
        ObservReportExcec-->|Bi-directional connection|GRPC
        GRPC-->|Bi-directional connection|ObservReportExcec
        ObservReportExcec-->ConfigReload
        ConfigReload-->|Reload for change|ConfigReload
        ObservReportExcec-->|Run tasks|Executor[Executor]
        ObservReportExcec-->|Run CronJobs|Cron[Cron]
        Cron-->Executor
        Executor-->|"Report back result (Events)"|ObservReportExcec
        ObservReportExcec-.->|Stay in sync|Serialization
        ObservReportExcec-.->|Stay in sync|Interactive
        ObservReportExcec-.->|Watch Update/Events from Scheduler|GRPC
    end
