sequenceDiagram
    participant git
    participant User
    participant CLI
    participant ConfigManagement
    participant TargetedServers
    Note over git,User: contains/has PlayBook object yamls
    git->ConfigManagement: notify about changes
    loop reconciliation
        ConfigManagement->ConfigManagement: create events with task info
    end
    loop watch and execute
        TargetedServers->ConfigManagement: watch events
        TargetedServers->TargetedServers: check if changes are needed
        alt changes needed?
            TargetedServers->TargetedServers: apply/run required changes
            TargetedServers->ConfigManagement: create "changes applied" event with results
            Note over TargetedServers,TargetedServers: with result info/state
        else
            TargetedServers->ConfigManagement: create "no changes" event
        end
        TargetedServers->TargetedServers: return to beginning of loop
    end
    User->CLI: trigger run
    Note left of CLI: CLI: Will only work if<br/>files are in a git repo
    CLI->ConfigManagement: create new version PlayBook object
    Note over CLI,TargetedServers: PlayBook object when created is "always" in a suspended state<br/>(toggleable by flag) A) apply the PlayBook to TargetedServers or<br/>B) apply PlayBook later
    ConfigManagement->ConfigManagement: go to reconciliation loop
